# Generated by Django 3.2.25 on 2024-10-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendancereport',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.staffenrollment'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.studentenrollment'),
        ),
    ]
