# Generated by Django 5.1.2 on 2024-10-16 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_alter_staffattendance_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.studentenrollment'),
        ),
    ]
